### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by PatrikMihalik** [spkesDE/tsvesync#1]
Hello,
some function of VeSync didnt work on device Dual 200S.
Fan change,ON/OFF function. mode selection. Just ON/OFF display is working.

Patrik

**Comment by spkesDE** [comment]
Could you try these functions again and **then** send a diagnostics report

**Comment by PatrikMihalik** [comment]
diagnostic report

189f0ea1-14de-4130-9823-5045622e5705

**Comment by spkesDE** [comment]
In your Homey App under More-> Apps-> VeSync ->Icon top right-> Send diagnostic report.

NVM: You got it.

**Comment by PatrikMihalik** [comment]
Thank you,I found it :-)

189f0ea1-14de-4130-9823-5045622e5705

**Comment by spkesDE** [comment]
So, please try this.

1. Remove your Dual200s
2. Install the test version https://homey.app/a/com.spkes.vesync/test/
3. Readd the device
4. Try to control the device
5. Send diagnostics report

**Comment by PatrikMihalik** [comment]
Still not working

In mode selection you have: off, manual,auto

O ml in humidifier is auto, low, high

ebfc7bc1-7bb8-498b-942f-2cc6a7513bc1

**Comment by spkesDE** [comment]
I just checked the diagnostics report.

Settings display on and off is working. This is the only thing that you did?

I don't see anything that you changed the mode via the homey app?


![image](https://user-images.githubusercontent.com/1682314/229485777-3fe3f1a2-350c-49b3-a874-3683133103d3.png)

this is a Classic 300s but a Dual200s also should have this capability.

**Comment by spkesDE** [comment]
Oh, my bad. Found this issue. 
install this version and it should work.
https://homey.app/a/com.spkes.vesync/test/

**Comment by PatrikMihalik** [comment]
Ok i try it, last one was the same problem. I sending report, i try next verison of app

**Comment by PatrikMihalik** [comment]
Now everything works, thanks a lot. Great work

**Comment by spkesDE** [comment]
Thank you for your help! Please feel free to update your review :)
